### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by bacaron** [dipy/bl_apps_dipy_track#1]
Tried running the Tracking using Probabilistic algorithm app and it failed due to exceeding available memory. Can we bump up the amount of memory requested? (see screenshot)

![Screen Shot 2020-08-24 at 4 20 26 PM](https://user-images.githubusercontent.com/22106265/91092275-c3b7c300-e625-11ea-9176-9e17ca37254c.png)

**Comment by guaje** [comment]
Increased to 20GB
